version: "3.8"

services:
  next:
    build:
      context: .
      target: next
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
