version: "3.8"

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules # Ne pas utiliser les node_modules de la machine hôte
    environment:
      - NODE_ENV=development
